export const ROUTER_LINKS = {
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  FORGOT_PASSWORD: "/forgot-password",
  NOT_FOUND: "/404",
  ROOT: "/dashboard",

  MAP: "/dashboard/map",
  UTILITIES: "/dashboard/utilities",
  ANALYTICS: "/dashboard/utilities/analytics",
  AWARENESS: "/dashboard/awareness",
  AWARENESS_PROGRAM: "/dashboard/awareness/<slug>",
  SCHEMES: "/dashboard/schemes",
  SCHEME: "/dashboard/schemes/<slug>",
  BLOGS: "/dashboard/blog",
  BLOG: "/dashboard/blog/<slug>",
  PROFILE: "/dashboard/profile",
  SETTINGS: "/dashboard/settings",
  NOTIFICATIONS: "/dashboard/notifications",
  HELP: "/dashboard/help",
  SUPPORT: "/dashboard/support",

  ADMIN: {
    ROOT: "/admin",
    DASHBOARD: "/admin/dashboard",
    USERS: "/admin/users",
    SECURITY: "/admin/security",
    ANOMALIES: "/admin/anomalies",
  },
};
